feat: build check用のCI追加
saitamau-maximum/maxitter pull request #41
Opened 2023-10-04 18:49 UTC by seiei-n

#33 
とりまfeat/*, fix/*, hotfix/* branchにプッシュした時にCIが走るようにした。
build cacheはつけてない。

2023-10-04 22:00 UTC, sor4chi requested changes
2点だけ頼む！

2023-10-04 22:00 UTC, sor4chi commented on .github/workflows/build-check.yml
> +            - hotfix/*
pull_requestでいいと思う

2023-10-04 22:00 UTC, sor4chi commented on .github/workflows/build-check.yml
> +              run: go build -o main .
これでも動きはするんですが、一応GoとNodejsは別なので別のjobsとして並列にやってみてもいいかも
hono-doのActionを参考にしてみてください

2023-10-04 22:41 UTC, a01sa01to reviewed
checkout, setup-node, setup-go のバージョンはもっと新しいのが出てるので最新版にしておくといいかも…？

2023-10-06 00:15 UTC, seiei-n commented on .github/workflows/build-check.yml
> +            - hotfix/*
修正しますた

2023-10-06 00:15 UTC, seiei-n commented on .github/workflows/build-check.yml
> +              run: go build -o main .
並列にしますた

2023-10-06 00:15 UTC, seiei-n commented
> checkout, setup-node, setup-go のバージョンはもっと新しいのが出てるので最新版にしておくといいかも…？

最新版にしますた

2023-10-06 00:32 UTC, sor4chi requested changes
確認お願い

2023-10-06 00:32 UTC, sor4chi commented on .github/workflows/build-check.yml
> +      types: [opened]
これだけだとpull request開いた時だけになっちゃわないか？

```yaml
on:
    pull_request:
```

だとpr内であれば再プッシュも含めて全てtriggerしてくれるよ

2023-10-06 00:34 UTC, seiei-n commented on .github/workflows/build-check.yml
> +      types: [opened]
なるほど

2023-10-06 00:35 UTC, seiei-n commented on .github/workflows/build-check.yml
> +      types: [opened]
修正しました

2023-10-06 00:35 UTC, sor4chi approved these changes
私はおけー

2023-10-06 01:13 UTC, a01sa01to approved these changes
CI cache はとりあえず後回しでいっか、おっけー！

2023-10-06 01:13 UTC, merged