投稿時間の表示機能を追加
saitamau-maximum/maxitter pull request #46
Opened 2023-10-05 05:58 UTC by batora9

投稿内容に投稿時間を加えて表示しました

2023-10-06 08:01 UTC, sor4chi requested changes
もうちょっと変更してみよう！

2023-10-06 08:01 UTC, sor4chi commented on frontend/src/components/Timeline.jsx
> +            <Typography variant="body1">{post.body} {post.created_at}</Typography>
表示自体は合ってます！
<img width="1512" alt="スクリーンショット 2023-10-06 16 46 54" src="https://github.com/saitamau-maximum/maxitter/assets/80559385/b429cb28-7b28-4f90-b3b4-892e37cd9ca0">

こんな感じで日付をもう少し小さくして縦並びにしてみましょう

2023-10-06 09:00 UTC, a01sa01to reviewed
development ブランチをこっちにマージしてほしいかも、ビルドチェックが効いてないので一応あったらいいかなーと

2023-10-06 13:44 UTC, sor4chi commented
@batora9 
自分のローカル環境で
```
git checkout feat-postedtime
git pull origin development
git push origin feat-postedtime
```
を実行してみてください

2023-10-08 15:21 UTC, sor4chi requested changes
もうひと頑張りです！整形処理自体は合っています！

2023-10-08 15:21 UTC, sor4chi commented on frontend/src/components/Timeline.jsx
> +
これはTimelineの中にある必要がない関数なので、Timelineコンポーネントの外側に出しましょう！

関数の中でposts, isLoding, fetchPostsなどのTimeline内にスコープがある変数を使いたい時は中に書かなければいけないので、全て外に出さないといけないわけではないことに注意してください。

2023-10-08 15:24 UTC, sor4chi requested changes
こちらもお願いします！

2023-10-08 15:24 UTC, sor4chi commented on frontend/src/components/Timeline.jsx
> +  const options = { year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" };
ごめんもう一点、タイムゾーンがちゃんと動いてませんでした！

optionsに`timeZone: "Asia/Tokyo"`を追加してみてください

2023-10-08 15:25 UTC, sor4chi commented on frontend/src/components/Timeline.jsx
> +  const options = { year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" };
変更前と変更後でスクショ撮っとくといいよ

2023-10-08 15:25 UTC, sor4chi commented on frontend/src/components/Timeline.jsx
> +  const options = { year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" };
明日の発表で使えるかも...？

2023-10-08 15:27 UTC, sor4chi approved these changes
ちゃんと時刻表示できてました、お疲れ様でした！

2023-10-08 23:10 UTC, a01sa01to approved these changes
LGTM!

2023-10-08 23:11 UTC, a01sa01to commented
修正したら「Resolve conversation」を押すようにしよう！

![image](https://github.com/saitamau-maximum/maxitter/assets/26807394/20f62dda-60ba-433e-b8b0-7253717d47ad)

2023-10-08 23:11 UTC, merged