feat: データベースにユーザテーブルを作成
saitamau-maximum/maxitter pull request #48
Opened 2023-10-05 16:05 UTC by kasa021

postsとusersのテーブルを作るクエリをファイル別にして作成しました。
emailとpasswordはユーザ認証のところにあったので、今回は追加してないです。
レビューお願いします。

2023-10-05 16:06 UTC, sor4chi commented
> emailとpasswordはユーザ認証のところにあったので、今回は追加してないです。
意図汲み取ってくれてありがとう

2023-10-05 16:13 UTC, sor4chi requested changes
ちょっと多くなってしまいましたが確認お願いします！

2023-10-05 16:13 UTC, sor4chi commented on backend/sql/1_create_post_table.sql
> +) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
EOLが削られてます！
この変更は動作に支障はないですがいらないので、練習も兼ねてrebaseとforce-pushを使いComiit履歴からこの変更を消す操作をしてみてください

コミットを綺麗に整理する練習です

2023-10-05 16:13 UTC, sor4chi commented on backend/sql/2_create_user_table.sql
> +) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
こちらもEOL消えてるので先ほどと同様ですね

2023-10-05 16:13 UTC, sor4chi commented on backend/sql/2_create_user_table.sql
> +  UNIQUE KEY `username` (`username`)
usernameがuniqueってことはtwitterのuser_idのようなものを想像してる感じ？
usernameは今のところuniqueである必要はないと思いますがどうですか？

2023-10-05 16:13 UTC, sor4chi commented on backend/sql/2_create_user_table.sql
> +  `bio` text DEFAULT NULL COMMENT '自己紹介',
bioをtextにすると文字数がめちゃくちゃ入れられるフィールドになってしまいますので、ここはvachar(1024)くらいにした方がいいかもしれない

2023-10-05 16:13 UTC, sor4chi commented on backend/sql/2_create_user_table.sql
> +  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
post側がcreated_atとupdated_atをアプリ側から決めるような設計になっているので、CURRENT_TIMESTAMP系の仕組みは今回はいらないと思います！

"投稿時間"を記録するか、"DB書き込み時間"を記録するかの違いになってきます

2023-10-05 16:28 UTC, kasa021 commented on backend/sql/2_create_user_table.sql
> +  UNIQUE KEY `username` (`username`)
usernameがuniqueである必要はないと思いましたね。

2023-10-05 16:28 UTC, kasa021 commented on backend/sql/2_create_user_table.sql
> +  `bio` text DEFAULT NULL COMMENT '自己紹介',
訂正します。

2023-10-05 16:29 UTC, kasa021 commented on backend/sql/2_create_user_table.sql
> +  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
訂正します。

2023-10-05 16:53 UTC, sor4chi approved these changes
修正してくれてありがとう、確実に成長を感じられて感動しました

2023-10-05 16:53 UTC, kasa021 commented
> 修正してくれてありがとう、確実に成長を感じられて感動しました

2023-10-06 00:08 UTC, a01sa01to approved these changes
👍

2023-10-06 00:08 UTC, merged