feat: Discord Webhook
saitamau-maximum/maxitter pull request #50
Opened 2023-10-06 06:25 UTC by yukikamome316

2023-10-06 07:06 UTC, a01sa01to commented on backend/post.go
> +	AVATER_URL = ""
`DISCORD_` とかつけるといいかも？
今後ごちゃごちゃしそうなので

2023-10-06 07:06 UTC, a01sa01to commented on backend/post.go
> +	whurl := getEnv("DISCORD_WEBHOOK_URL", "")
`whurl` -> `webhook_url` とかにしてもいいかも

2023-10-06 07:06 UTC, a01sa01to commented on backend/post.go
> +	dw := &webhook.DiscordWebhook{
`dw` -> `discord_webhook` ?

2023-10-06 07:06 UTC, a01sa01to commented on backend/post.go
> +	if !sendPostWebhook(post) {
内部でエラー出力せずに error を返すようにして、

```go
if err := sendPostWebhook(post); err != "" {
```

にした方がいい気がした

2023-10-06 07:06 UTC, a01sa01to commented on backend/webhook/webhook.go
`sendPostWebhook` はこっちにあってもいいのかもと思った
要検討

2023-10-06 07:08 UTC, a01sa01to commented on backend/post.go
> +	whurl := getEnv("DISCORD_WEBHOOK_URL", "")
や、今後もいろいろ webhook 追加するかもしれないので `discord_` もつけたほうがいいのかも？

2023-10-06 07:19 UTC, sor4chi requested changes
確認お願いします！

2023-10-06 07:19 UTC, sor4chi commented on backend/webhook/webhook.go
もしこのファイル分けたいなら、`webhook/webhook.go`は限定的すぎるので`interface/discord.go`とかにした方がいいかも

2023-10-06 07:19 UTC, sor4chi commented on backend/Dockerfile
> +CMD ["go", "run", "main.go", "migration.go", "post.go"]
エンドポイント（機能）単位でファイル切り分けるのどうかなって思った...
Goはパッケージ思考なので機能集約で配置するよりは
層集約のような同じ役割を持つものを同じパッケージに配置するような傾向が強いと思うので相談したい

@a01sa01to

2023-10-06 07:19 UTC, sor4chi commented on backend/webhook/webhook.go
> +)
型定義めちゃくちゃ多くなってるけどdiscordのgoクライアントってないのかな？

2023-10-06 07:19 UTC, sor4chi commented on .env.example
> +DISCORD_WEBHOOK_URL="https://discord.com/api/webhooks/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
ここは良かったと思う、ナイス

ただ全員がwebhookURL持ってるわけでもないので、webhookが設定されてない時は警告を出しつつも動くみたいな感じにするのが理想なんじゃないですかね。

2023-10-06 07:25 UTC, a01sa01to commented on backend/Dockerfile
> +CMD ["go", "run", "main.go", "migration.go", "post.go"]
それはそうだよなぁ
ただ API が増えてきた時にどこにハンドラ関数があるか探すのめんどくさそうだなーと思ったり (ISUCON で慣れてしまっているけども)

2023-10-06 07:26 UTC, a01sa01to commented on backend/webhook/webhook.go
https://github.com/saitamau-maximum/maxitter/pull/50#discussion_r1348330257
こっちのほうがいいのでやっぱりなしで

2023-10-06 07:49 UTC, sor4chi commented on backend/Dockerfile
> +CMD ["go", "run", "main.go", "migration.go", "post.go"]
もっというとmigrationも本当は`cmd/migration/main.go`におきたい

2023-10-09 06:06 UTC, yukikamome316 commented on backend/webhook/webhook.go
> +)
よさそうなものがすぐに見つからなかったので、いったんこのままにしておきます。

2023-10-09 08:43 UTC, a01sa01to approved these changes

2023-10-14 16:19 UTC, sor4chi reviewed
OK~

2023-10-14 16:19 UTC, sor4chi submitted a review, later dismissed

2023-10-15 23:03 UTC, a01sa01to requested changes
@yukikamome316 なんか conflict 起きてる

2023-10-17 00:07 UTC, yukikamome316 commented on backend/Dockerfile
> +CMD ["go", "run", "main.go", "migration.go", "post.go"]
> もっというとmigrationも本当は`cmd/migration/main.go`におきたい
@sor4chi 
このように切り離した場合、どうやってcmd/migration/main.goを実行させます

2023-10-17 12:49 UTC, sor4chi commented on backend/Dockerfile
> +CMD ["go", "run", "main.go", "migration.go", "post.go"]
deployスクリプトでdocker runするかdocker composeファイルのcmdでserver起動する前に走らせるかな

2023-10-17 13:16 UTC, yukikamome316 commented on backend/Dockerfile
> +CMD ["go", "run", "main.go", "migration.go", "post.go"]
別ブランチを切って対処します

2023-10-21 08:03 UTC, a01sa01to commented on backend/migration.go
なんか消されてるの気になる？

2023-10-21 09:04 UTC, yukikamome316 commented on backend/migration.go
可読性の問題からとりあえずmain.goに統一することにしました。
後に別ブランチにて`cmd/migration/main.go`に移行する予定です！

2023-10-21 13:39 UTC, sor4chi commented on backend/migration.go
それが良さそう。タスクは細分化したほうがいい

2023-10-22 00:39 UTC, a01sa01to approved these changes

2023-10-22 00:42 UTC, a01sa01to commented on backend/migration.go
ok~

2023-10-22 06:04 UTC, sor4chi approved these changes
OK!

2023-10-22 06:04 UTC, merged