投稿件数を数える機能を追加
saitamau-maximum/maxitter pull request #51
Opened 2023-10-07 16:54 UTC by shigekk

投稿件数を数えるところまでは出来たかと思います。
表示するところは、まだです

2023-10-08 02:10 UTC, a01sa01to requested changes
ひとまずお願いします！

2023-10-08 02:10 UTC, a01sa01to commented on backend/main.go
> +	api.GET("/counts-posts",h.Count)
`/count-posts` にしたほうがいいかも

2023-10-08 02:10 UTC, a01sa01to commented on backend/main.go
> +func (h *Handler) Count(c echo.Context) error {
`Count` だけだとよくわからないので、 `CountPosts` にするとわかりやすくて Good

2023-10-08 02:42 UTC, sor4chi commented on backend/main.go
> +	api.GET("/counts-posts",h.Count)
そしたら`/posts/count`の方が良くないか？

2023-10-08 02:51 UTC, a01sa01to commented on backend/main.go
> +	api.GET("/counts-posts",h.Count)
それはそうだわ

2023-10-23 07:58 UTC, sor4chi requested changes
いくつか確認お願いします（間違えてたらすみません）

2023-10-23 07:58 UTC, sor4chi commented on backend/main.go
> +	api.POST("", h.CreatePost)
ここ`apiPosts.POST`じゃないですかね？
これだと/posts配下のパスじゃなくなる気がします

```suggestion
	apiPosts.POST("", h.CreatePost)
```

2023-10-23 07:58 UTC, sor4chi commented on backend/main.go
> +func (h *Handler) Count(c echo.Context) error {
@shigekk 
これ治せそうですか？

2023-10-23 07:58 UTC, sor4chi commented on frontend/src/App.jsx
> +    console.log(data);
これはいらないので消しちゃって良さそうです！

2023-10-23 07:58 UTC, sor4chi commented on frontend/src/components/CountPost.jsx
> +    // }
これもいらないので消しちゃいましょう

2023-10-23 15:33 UTC, a01sa01to reviewed
あくまで個人の感想です
あと全体的に演算子の前後にはスペース空けましょう！

2023-10-23 15:33 UTC, a01sa01to commented on backend/main.go
> +	apiPosts.POST("", h.CreatePost)
`/posts` は `/posts` でまとめたい気がする？

2023-10-23 15:33 UTC, a01sa01to commented on backend/main.go
> +func (h *Handler) Count(c echo.Context) error {
これ直ってないっぽいです

2023-10-23 15:33 UTC, a01sa01to commented on frontend/src/App.jsx
> +  const [amount, setAmount] = useState(0);
postCount にしたほうがわかりやすい気はした (が、変える必要があるのかと問われると微妙)

2023-10-23 15:33 UTC, a01sa01to commented on frontend/src/App.jsx
> +        />
これ、投稿件数がそれなりにあると見づらいと思うので上に持ってきちゃってもいいかもです (具体的には「更新する」の下とか？)

2023-10-30 10:12 UTC, shigekk commented on frontend/src/App.jsx
> +        />
投稿件数を見たいというシチュエーションがあまり思い浮かばないので，下の方がいいかと思っているのですが，どうでしょうか．

2023-10-30 10:18 UTC, sor4chi requested changes
他はよかったです、一点だけお願いします！

2023-10-30 10:18 UTC, sor4chi commented on frontend/src/App.jsx
> +  const [amount, postCount] = useState(0);
これはreactの慣習になっちゃうんだけど、この場合`[postCount, setPostCount]`のように命名すると良いです！

2023-10-31 05:12 UTC, a01sa01to commented on frontend/src/App.jsx
> +        />
まあこれは個人の好みなのでどちらでも... (変更依頼ではないです)

2023-11-02 09:03 UTC, a01sa01to requested changes

2023-11-02 09:03 UTC, a01sa01to commented on backend/main.go
> +    }
いらないはず？

2023-11-03 01:20 UTC, a01sa01to commented on backend/main.go
> +    }
いらないというよりかは `/api/posts` と `/api/posts/count` で重複するから `/api/posts` の方は消した方が良さそう、のほうが正しいかも

2023-11-06 07:40 UTC, shigekk commented on backend/main.go
> +    }
重複を消しました．
GetPostsで投稿と投稿件数を返すようにしました．

2023-11-06 14:04 UTC, a01sa01to commented on backend/main.go
> +    }
あーそうではなく、 GetPosts では投稿件数はいらなくて、 CountPosts だけで取れればおっけーという意図です

2023-11-10 01:22 UTC, a01sa01to approved these changes

2023-12-04 08:47 UTC, sor4chi approved these changes
LGTM

2023-12-10 10:50 UTC, merged