仮のロゴを設置
saitamau-maximum/maxitter pull request #55
Opened 2023-10-08 16:06 UTC by hana-rs

2023-10-08 16:27 UTC, sor4chi requested changes
素敵なロゴありがとう！いくつかお願いします！

2023-10-08 16:27 UTC, sor4chi commented on mini.PNG:Zone.Identifier
> +ZoneId=3
このファイルはなんでしょうか

もし必要ないやつだったら削除してコミットすると消せるのでやってみてください！

2023-10-08 16:27 UTC, sor4chi commented on frontend/karilogo.PNG
画像ファイルは`fronteend/public`フォルダにおいた方が後々嬉しいのでできればそちらへ移動して欲しいです！

2023-10-08 16:27 UTC, sor4chi commented on frontend/index.html
> +    </header>
ヘッダまで作ってくれてありがとう、alt属性までついていいと思います

2023-10-08 16:27 UTC, sor4chi commented on frontend/index.html
> +    </header>
Reactの方へ移植するのが必要そうですが、また別タスクでやりましょう！

2023-10-08 23:19 UTC, a01sa01to requested changes
お願いします！

2023-10-08 23:19 UTC, a01sa01to commented on frontend/public/karilogo.PNG
いいロゴ！ 一般的に拡張子は小文字なので、小文字にしていただけると！

2023-10-08 23:19 UTC, a01sa01to commented on frontend/index.html
> +      <a href="">
これだと現在いるページを再読み込みする挙動になっているので、リンク先としてトップページ (`/`) を指定するとベターかなと思いました～

```suggestion
      <a href="/">
```

2023-10-09 04:17 UTC, sor4chi commented on frontend/index.html
> +      <a href="">
気づかなかった！

2023-10-09 08:20 UTC, a01sa01to approved these changes
LGTM!
細かいところけど、コミットはなるべく細分化したほうが嬉しかったりします～ (もしバグったときに後戻りしやすいので)

2023-10-09 10:36 UTC, hana-rs commented
了解です

> LGTM! 細かいところけど、コミットはなるべく細分化したほうが嬉しかったりします～ (もしバグったときに後戻りしやすいので)

2023-10-09 10:52 UTC, sor4chi approved these changes
お疲れ様でした！

2023-10-09 10:55 UTC, merged