Feature pagenation
saitamau-maximum/maxitter pull request #59
Opened 2023-10-09 08:41 UTC by nakamuraitsuki

コミット細分化を忘れていて長くて見ずらいコミットメッセージになりました。
すみません。
動作確認の段階でReactのほうもそれなりに動くようになっているみたいです

2023-10-09 09:45 UTC, a01sa01to requested changes

2023-10-09 09:45 UTC, a01sa01to commented on backend/main.go
> +	page, _ := strconv.Atoi(pageParam)
もし数字以外が返されたらエラーが吐かれるので、そうなった場合はステータスコードとして 400 (Bad Request) を返すようにしましょう！

2023-10-09 09:45 UTC, a01sa01to commented on backend/main.go
> +var Index = 0
81 行目で `index := page * 20` となっているので、この行は不要なはず？

2023-10-09 09:45 UTC, a01sa01to commented on backend/main.go
> +	Index := (page) * 20
変数名は camelCase が推奨されているので、 `index` に変更してほしいです！
それと `page` には括弧をつける必要はないので外すと読みやすくなってうれしいです

```suggestion
	index := page * 20
```

2023-10-09 09:45 UTC, a01sa01to commented on backend/main.go
> +	query := fmt.Sprintf("SELECT * FROM posts ORDER BY created_at DESC LIMIT 20 OFFSET %d", Index)
今回は大丈夫ですが、悪意のある人が変な値 `20; SELECT * FROM users` と入れると、`SELECT * FROM posts ORDER BY created_at DESC LIMIT 20 OFFSET 20; SELECT * FROM users` となってしまいます。
これにより、ユーザー情報などが取得されてしまうという脆弱性になります。
これは「SQL インジェクション」と呼ばれます (詳しくは調べてみてください)。

そこで「プレースホルダ」機能を使うと安全です。プレースホルダを使って書き換えてみてください！

2023-10-09 09:49 UTC, a01sa01to commented
ひとまず frontend 側は #51 との兼ね合いもあるのでいったん置いておくことにしましょう (戻しておいていただけると助かります～！)

2023-10-09 13:43 UTC, a01sa01to requested changes
あと少し！お願いします！

2023-10-09 13:43 UTC, a01sa01to commented on backend/main.go
> +	err = h.DB.Select(&posts, "SELECT * FROM posts ORDER BY created_at DESC LIMIT 20 OFFSET index = ?", index)
構文が違う気がしますー (`index = ` がいらない気がする？)

2023-10-09 13:43 UTC, a01sa01to commented on frontend/src/App.jsx
frontend 側戻しきれてないっぽいので戻していただけるとレビュー時に助かります～ (https://github.com/saitamau-maximum/maxitter/blob/development/frontend/src/App.jsx からコピペするのが確実)

2023-10-09 14:10 UTC, nakamuraitsuki commented on backend/main.go
> +	err = h.DB.Select(&posts, "SELECT * FROM posts ORDER BY created_at DESC LIMIT 20 OFFSET index = ?", index)
ありがとうございます。

2023-10-11 09:27 UTC, a01sa01to commented on backend/main.go
> +	}
page パラメータに指定がない場合、私の知る限り

- 400 Bad Request を返す
- page = 1 とする (最初のページを読み込む; 今記述してもらった処理)
- 全件返す

という実装がメジャーだと思ってます (参考までに)。

で、全件返すのは明らかに論外なので、個人的にはこういうとき、 frontend 側から呼ぶときは page があることが保証されているので 400 を返したいな～と思っているんですが、 page = 0 を返してもいい気はしてます (どうしよ @sor4chi )

2023-10-11 09:28 UTC, a01sa01to requested changes
すみません！お願いします！

2023-10-11 09:28 UTC, a01sa01to commented on backend/main.go
> +	page, err := strconv.Atoi(pageParam)
今気づいたんですが、Atoi だと page にマイナスを入れてもエラーが起きず、その後の処理が変になる気がします
なので `strconv.ParseUint` (符号なし整数型) を使ったほうがいい気がしました

参考: https://pkg.go.dev/strconv#ParseUint

2023-10-14 16:17 UTC, sor4chi approved these changes
OK

2023-10-14 16:17 UTC, sor4chi commented on backend/main.go
> +	page, err := strconv.Atoi(pageParam)
同意です

2023-10-14 16:17 UTC, sor4chi commented on backend/main.go
> +	}
パラメータが指定されていない -> page = 1
パラメータが範囲外 -> `400 Bad Request` or `404 Not Found`

私は404推し

2023-10-15 03:52 UTC, a01sa01to approved these changes

2023-10-15 04:56 UTC, kasa021 approved these changes

2023-10-15 23:04 UTC, merged