仮ロゴをindex.htmlからApp.jsxに移行
saitamau-maximum/maxitter pull request #73
Opened 2023-10-15 15:57 UTC by hana-rs

2023-10-15 22:50 UTC, sor4chi requested changes

2023-10-15 22:50 UTC, sor4chi commented on frontend/src/App.jsx
> +      <div
`className="App"`はいらないかも！
headerとaタグは残していいと思う！

2023-10-15 22:54 UTC, a01sa01to requested changes
お願いしますー

2023-10-15 22:54 UTC, a01sa01to commented on frontend/src/App.jsx
> +       className="App">
className="App" だとなんかかぶりそう (気にしすぎかも)

2023-10-15 22:54 UTC, a01sa01to commented on frontend/src/App.jsx
> +      <div
元が header だから header でもいいと思う

2023-10-15 22:54 UTC, a01sa01to commented on frontend/src/App.jsx
> +      <div
たぶん `<ColorModeProvider />` の中 `<CssBaseline />` の下に書いたほうがよさそう？
カラーモードが反映されない気がするので

2023-10-15 22:55 UTC, a01sa01to commented on frontend/src/App.jsx
> +          <img src='../public/karilogo.png' width="200"  height="60" className="App-logo" alt="karilogo" />
Link が貼られてないので... と思ったけど React Router 導入してなかったので後でやりましょうかね

2023-10-15 22:56 UTC, sor4chi commented on frontend/src/App.jsx
> +      <div
2

2023-10-15 22:59 UTC, a01sa01to commented on frontend/src/App.jsx
> +      <div
それいったら GlobalStyles の下に ToggleTheme 置いたほうがいい気もしてるけどこれは適当に直しておきましょうかね

2023-10-16 11:02 UTC, a01sa01to approved these changes, later dismissed

2023-10-16 11:07 UTC, sor4chi requested changes
一点だけお願い！他は良かったです！

2023-10-16 11:07 UTC, sor4chi commented on frontend/src/components/Logo.jsx
> +export const Logo = () => {
Logoっていうコンポーネント名よりはHeaderっていうコンポーネント名の方がいいかも

2023-10-16 11:07 UTC, sor4chi commented on frontend/src/components/Logo.jsx
> +export const Logo = () => {
ついでにファイル名もLogo.jsxからHeader.jsxにしてもらえると🙆‍♀️

2023-10-16 12:10 UTC, a01sa01to commented on frontend/src/components/Logo.jsx
> +export const Logo = () => {
🦀

2023-10-17 08:20 UTC, sor4chi approved these changes, later dismissed
LGTM！お疲れ様でした〜

2023-10-17 08:21 UTC, hana-rs commented
> LGTM！お疲れ様でした〜

ありがとうございました！

2023-10-21 08:01 UTC, a01sa01to approved these changes
みのがしてたー！？おつかれさまでした！

2023-10-21 08:03 UTC, a01sa01to requested changes
あーいや、なんか Conflict 起きてるっぽいので直してくださいー！
`git pull origin development` していい感じに編集すればおっけーです
 
![image](https://github.com/saitamau-maximum/maxitter/assets/26807394/4d991f1c-8207-4c75-b784-8ede63aafcbf)

2023-10-22 02:52 UTC, hana-rs commented
> あーいや、なんか Conflict 起きてるっぽいので直してくださいー！ `git pull origin development` していい感じに編集すればおっけーです   ![image](https://user-images.githubusercontent.com/26807394/277095855-4d991f1c-8207-4c75-b784-8ede63aafcbf.png)

自分でやってみたんですけど治ってないぽいですかねこれ

2023-10-22 05:21 UTC, a01sa01to commented
治ってないっぽいですね... `frontend/index.html` を見てみるとよさそう

2023-10-22 06:27 UTC, sor4chi commented
`git config pull.rebase false`の説明をしたほうが良さそう？

2023-10-22 06:36 UTC, hana-rs commented
@a01sa01to @sor4chi

 git pull origin developmentしたあと、
 
<<<<<<< feat-reactlogo
=======
    <header>
      <a href="/">
        <img src="karilogo.png" width="200" height="60" alt="karilogo" />
      </a>
    </header>
>>>>>>> development
を、全消しして、アドしてコミットしてプッシュでいいですか？

git config pull.rebase falseの説明、欲しいです。

2023-10-22 07:37 UTC, a01sa01to approved these changes
ヨシ！お疲れさまでした！
(見ちゃったので一応言っておくと、 ` 3 つで囲うとコードブロックになります ↓)

```
<<<<<< aaa
xxx
------
yyy
>>>>>> bbb
```

2023-10-22 07:41 UTC, hana-rs commented
> ヨシ！お疲れさまでした！ (見ちゃったので一応言っておくと、 ` 3 つで囲うとコードブロックになります ↓)
> 
> ```
> <<<<<< aaa
> xxx
> ------
> yyy
> >>>>>> bbb
> ```

消してたのにバレてて笑いました
ありがとうございます…笑笑笑

2023-10-22 07:47 UTC, sor4chi approved these changes
LGTM
コンポーネント分割の方法とか色々並べてそうでよかったです

2023-10-22 07:48 UTC, merged