backend: Postのcreated_atをJSTに
saitamau-maximum/maxitter pull request #74
Opened 2023-10-15 18:22 UTC by Daaaai0809

2023-10-15 22:23 UTC, sor4chi commented
![スクリーンショット 2023-10-16 7 22 44](https://github.com/saitamau-maximum/maxitter/assets/80559385/22f3c263-168d-41df-9b63-f38e1850245e)

なぜ共著？

2023-10-15 22:25 UTC, sor4chi requested changes
これはダメかなー

2023-10-15 22:25 UTC, sor4chi commented on backend/main.go
> +	setJST()
タイムゾーンはブラウザ側のユーザー設定で動的に変更して表示するのが一般的だと思う
基本ブラウザ側でUTCに変えてPost -> バックでUTCで保存 -> フロントにUTC返却 -> フロントでブラウザタイムゾーン変換 -> 表示

2023-10-15 22:26 UTC, sor4chi commented on backend/main.go
> +	setJST()
日本の人だけが使うって確定してるサービスじゃないとこれはやらないかなー

2023-10-15 22:45 UTC, a01sa01to requested changes

2023-10-15 22:45 UTC, a01sa01to commented on backend/main.go
> +	setJST()
2

2023-10-15 22:49 UTC, sor4chi commented on backend/main.go
> +	setJST()
ちなみにブラウザ側でcreated_at取らない理由はパソコンにぞかんは自由に変えられるからdす

2023-10-30 10:56 UTC, sor4chi approved these changes
OK!

2023-10-30 10:57 UTC, sor4chi requested changes
CI落ちてます

2023-10-30 14:18 UTC, a01sa01to requested changes
これだけおねがいー

2023-10-30 14:18 UTC, a01sa01to commented on frontend/src/App.jsx
> +    setPosts([post, ...posts]);
trailing space

```suggestion
    setPosts([post, ...posts]);
```

2023-10-31 00:04 UTC, sor4chi approved these changes
お疲れ様でした！こちらでもちゃんと動きました

2023-10-31 01:27 UTC, a01sa01to approved these changes

2023-10-31 01:28 UTC, a01sa01to commented
あとは Resolve Conversation してもらえれば 🙆

2023-10-31 02:05 UTC, merged