style: prettier を導入
saitamau-maximum/maxitter pull request #76
Opened 2023-10-16 10:55 UTC by a01sa01to

2023-10-16 10:56 UTC, sor4chi requested changes
`.vscode`にsuggest extension書いて

2023-10-16 11:01 UTC, sor4chi requested changes

2023-10-16 11:01 UTC, sor4chi commented on .vscode/extensions.json
> +    "esbenp.prettier-vscode"
あ。ごめんすでに設定してたw

2023-10-16 11:03 UTC, a01sa01to commented on .vscode/extensions.json
> +    "esbenp.prettier-vscode"
😠

2023-10-16 11:05 UTC, sor4chi approved these changes
ご迷惑おかけしました、大変申し訳ありませんでした。

2023-10-17 08:03 UTC, seiei-n approved these changes

2023-10-17 08:20 UTC, merged