Feat/react routerを導入しました
saitamau-maximum/maxitter pull request #77
Opened 2023-10-18 01:34 UTC by kasa021

react-router導入して、ルートを増やせるようにした。
nginx/prod/conf.d/maxitter.confに `try_files $uri $uri/ /index.html` これが書いてあってリロードしても404が返されないようになってた。フォールバック設定って404が返ってこないようにするってことであってるよね？

レビューお願いします。

2023-10-18 01:38 UTC, sor4chi requested changes
nginxの設定(spa fallback)が必要になります、まだ月曜まで時間あるのでできるかは別として調べてみてほしいです。

2023-10-18 01:39 UTC, sor4chi commented
> nginx/prod/conf.d/maxitter.confに try_files $uri $uri/ /index.html これが書いてあってリロードしても404が返されないようになってた。フォールバック設定って404が返ってこないようにするってことであってるよね？

書いてあった、そうです！

2023-10-30 09:03 UTC, kasa021 commented
> nginxの設定(spa fallback)が必要になります、まだ月曜まで時間あるのでできるかは別として調べてみてほしいです。

終わってるので、マージして欲しいです。

2023-10-30 09:17 UTC, sor4chi commented
@kasa021 
別タスクとしてやるってこと？issue作ったらmergeしていいよ

2023-10-30 09:17 UTC, sor4chi approved these changes

2023-10-30 09:18 UTC, sor4chi requested changes

2023-10-30 09:18 UTC, sor4chi commented on frontend/src/main.jsx
> +    </Router>
`main.jsx`はAppだけを読んで、`app.jsx`の中でreact-routerを設定してほしい

2023-10-30 09:18 UTC, sor4chi commented
これだけお願い

2023-10-30 09:23 UTC, kasa021 commented
> @kasa021 別タスクとしてやるってこと？issue作ったらmergeしていいよ

いや、フォールバックの設定は元々されてたっていうこと。

2023-10-30 10:48 UTC, sor4chi approved these changes

2023-10-30 10:48 UTC, sor4chi commented on frontend/src/App.jsx
> +                </Container>
これをpages/*へ切るっていう条件付きでApprove

2023-10-30 10:49 UTC, merged

2023-10-30 15:28 UTC, kasa021 commented on frontend/src/main.jsx
> +    </Router>
thanks

2023-10-30 23:58 UTC, sor4chi commented on frontend/src/App.jsx
> +                </Container>
@kasa021 これ次できる？

2023-10-31 05:09 UTC, kasa021 commented on frontend/src/App.jsx
> +                </Container>
了解