仮ロゴを正規ロゴに置き換え
saitamau-maximum/maxitter pull request #80
Opened 2023-10-23 07:36 UTC by hana-rs

ロゴのパスも直しました！レビューお願いします。

2023-10-23 07:42 UTC, sor4chi approved these changes, later dismissed
すげえええ！！！！！

2023-10-23 14:42 UTC, a01sa01to approved these changes
すげー！しかもちゃんと SVG になってる！！

2023-10-23 14:45 UTC, a01sa01to commented on frontend/src/components/Header.jsx
>          </header>
ちょっと気になったんだけど、この SVG が 1068x196 (左側の余白を切り取れば少し減るかもだけど) なので height=60 だと width=327 くらいな気がする → もしかしたら潰れない？

2023-10-23 15:21 UTC, a01sa01to commented on frontend/src/components/Header.jsx
>          </header>
潰れずに width=200 が優先されて上下 margin が追加されてるっぽい...？

2023-10-24 02:31 UTC, hana-rs commented on frontend/src/components/Header.jsx
>          </header>
左側の余白は、それ無しだと極端に左につめた形になっちゃったのでfigmaでわざと追加しました。
heightとwidthの値は変えても潰れることはないです。上下に余白があるなと思いました。
![image](https://github.com/saitamau-maximum/maxitter/assets/132898015/5410d1d0-6b2c-44f5-a0e7-818f21a195c2)
![image](https://github.com/saitamau-maximum/maxitter/assets/132898015/3cb10433-c4b0-4b50-90d8-20d6864140e0)

2023-10-24 04:59 UTC, sor4chi commented on frontend/src/components/Header.jsx
>          </header>
です！外側の余白がmargin、内側の余白がpaddingで、その二つで調節する感じになるので、画像は余白のことを考慮しなくても大丈夫な感じです！

2023-10-25 01:25 UTC, a01sa01to commented on frontend/src/components/Header.jsx
>          </header>
それって CSS で指定したほうがいい気がするんだけどどうなんだろ @sor4chi

2023-10-25 01:42 UTC, sor4chi commented on frontend/src/components/Header.jsx
>          </header>
そうだよ

2023-10-25 02:06 UTC, a01sa01to commented on frontend/src/components/Header.jsx
>          </header>
@hana-rs ということなので SVG 内の余白は取り除いちゃってください！スタイルはとりあえず後でやりましょう～

2023-10-27 02:03 UTC, a01sa01to requested changes
(コメントに書いたけど変えてなかったので Request Changes)

2023-10-30 09:47 UTC, hana-rs commented
とりあえず余白だけなんとかしました。
ずっとグループ化してやってたらトリミングがうまくいかなくて手こずったんですが、フレーム化したら解決しました。
Figmaむずかしいです。

あとロゴちょっと大きめにしました。

2023-10-30 09:53 UTC, sor4chi approved these changes
![スクリーンショット 2023-10-30 午後6 53 14](https://github.com/saitamau-maximum/maxitter/assets/80559385/f28a4f0b-eea7-48af-b9ee-81c9fbe4fe68)
NICE

2023-10-30 10:49 UTC, merged