Feat/ユーザーを選ぶセレクトボックスを追加
saitamau-maximum/maxitter pull request #83
Opened 2023-10-23 14:16 UTC by nakamuraitsuki

一度間違えてdevelopmentからブランチを切って開発してしまい、あとからproject-userからブランチを切ってそこにマージしました。
順序無視してすみません。よろしくお願いします。

2023-10-23 15:36 UTC, a01sa01to commented
> あとからproject-userからブランチを切ってそこにマージしました。

そしたら base branch として `development` じゃなくて `feat/project-user` を指定したほうがいい気がします～
タイトル右の Edit から変更できます！

![image](https://github.com/saitamau-maximum/maxitter/assets/26807394/1cdb98d9-0787-44cd-8f62-5b23bb0336f5)

2023-10-26 04:35 UTC, sor4chi requested changes
お願いします

2023-10-26 04:35 UTC, sor4chi commented on frontend/src/components/UserSelectBox.jsx
> +      <MenuItem value = {user.id}>{user.username}</MenuItem>
reactはmapなどを使って繰り返し要素を生成する場合に`key`というpropsを設定することが推奨されています。
```suggestion
      <MenuItem value={user.id} key={user.id}>{user.username}</MenuItem>
```
これは並び替えなどが発生した時などに使われる要素特定用のものでしてないといろいろ動かなくなってしまうことがあるためつけた方がいいです。
一意な値であるべきなのでidを使うと良いと思います

2023-10-26 04:35 UTC, sor4chi commented on frontend/src/components/UserSelectBox.jsx
> +      <MenuItem value = {user.id}>{user.username}</MenuItem>
apiの通信結果を見る感じ、`username`ではなく`name`の気がしますが、そちらでは動いていますか？

2023-10-29 01:37 UTC, nakamuraitsuki commented on frontend/src/components/UserSelectBox.jsx
> +      <MenuItem value = {user.id}>{user.username}</MenuItem>
すみません。dbのユーザーテーブルのところの名前でやるものだと勘違いしてました。動いてなかったので修正します

2023-10-29 04:25 UTC, sor4chi commented on frontend/src/components/UserSelectBox.jsx
> +      <MenuItem value = {user.id}>{user.username}</MenuItem>
これはトラップですね...
nakamuraくんがやってくれたよりも前の誰かのPRの時に自分が「DBのカラム名と違うのは分かりづらいので避けましょう」という指摘をした方が良かった...すみません

もし可能だったらこの後別issueでリファクタリングのタスクとして直してくれてもいいんですよ👀

2023-10-29 04:26 UTC, sor4chi approved these changes
LGTM!

2023-10-29 07:09 UTC, a01sa01to commented on frontend/src/components/UserSelectBox.jsx
> +      <MenuItem value = {user.id}>{user.username}</MenuItem>
圧力...

2023-10-29 08:21 UTC, a01sa01to approved these changes

2023-10-29 08:21 UTC, merged