feat/投稿する際にUserIDを一緒に送る
saitamau-maximum/maxitter pull request #93
Opened 2023-11-04 07:30 UTC by nakamuraitsuki

URLを使って送るようにしました。
最初勘違いをしていて無駄なコミットが多数存在します。

2023-11-05 04:16 UTC, a01sa01to requested changes

2023-11-05 04:16 UTC, a01sa01to commented on frontend/src/components/Form.jsx
>        body: JSON.stringify({ body }),
HTTP method が POST のときは、データはクエリパラメータ (URL に `?` をつけて送るやつ) よりも、 body に付加するのが一般的です (詳しくは [MDN Web Docs](https://developer.mozilla.org/ja/docs/Web/HTTP/Methods) あたりを見ると良いと思います)

2023-11-06 01:42 UTC, sor4chi commented on frontend/src/components/Form.jsx
>        body: JSON.stringify({ body }),
（POSTエンドポイントのクエリパラメータに識別子情報を載せるように設計すると、人的なセキュリティリスクが発生しやすくなるという懸念もあります。識別子は認証トークンやセッションから取りましょうという話）
こういう理由でこの方法が使われてないんです

2023-11-09 13:15 UTC, sor4chi approved these changes
良さそう

2023-11-10 01:20 UTC, a01sa01to approved these changes

2023-11-10 01:20 UTC, merged