feat: 簡易的にBunとマイグレーションを導入
saitamau-maximum/maxitter pull request #96
Opened 2023-11-08 16:15 UTC by yukikamome316

必要最低限で動く程度に導入しました。
APIの仕様は変わっていません。

2023-11-08 23:39 UTC, sor4chi reviewed
cmd/serverいかにロジックが詰められてる状態になってるから
handlerはhandler.goをrootに作ってそれを呼び出すような形にするといいかも

2023-11-09 02:12 UTC, sor4chi commented
よさそう、後でみます

2023-12-14 05:32 UTC, yukikamome316 commented
コンフリクト解消したのでレビューお願いします

2023-12-14 06:30 UTC, sor4chi requested changes
まずレビュー進める前にドキュメント追加してください！

2023-12-14 06:56 UTC, sor4chi requested changes
とりあえずこれだけ

2023-12-14 06:56 UTC, sor4chi commented on scripts/migrate.sh
`migrater.sh` にしよう
`migrate.sh migrate`とかいう呼び出し型になってしまっている
ついでにDOCSも変えてもろて

2023-12-14 06:56 UTC, sor4chi commented on README.md
マイグレーションの記述に関してのドキュメントが少ないかも
例えばテーブル追加したいと思った時に担当者に聞くみたいなのを無くさないといけないので、ここを読んでください（公式ドキュメントを貼る）とか、そういうこのコード知らない人目線でどう書けば自分に質問が飛んでこないか考えてみるといいと思う

2023-12-14 06:56 UTC, sor4chi commented on backend/Dockerfile
prod buildしたときに動かんくないこれだと
entryの位置変わってるので`go build -o main .`が動かなさっそう

2023-12-18 05:38 UTC, sor4chi requested changes
一つだけ

2023-12-18 05:38 UTC, sor4chi commented on README.md
> +    このようにすることでマイグレーションをロールバックすることができるようになるため、バージョン管理が容易になるというメリットがあります。
upした内容をdownで完全にcleanupできるように書きましょうという注意書きを書いた方が良さそう

2023-12-18 05:38 UTC, sor4chi commented
@a01sa01to レビューできる？もし時間なかったら他の人に振ってもOK

2023-12-18 06:14 UTC, sor4chi approved these changes

2023-12-18 06:52 UTC, a01sa01to approved these changes
みてなかったー、たぶん OK

2025-09-06 15:14 UTC, closed without merging

2025-09-06 15:15 UTC, yukikamome316 commented
ソースコードが複雑になると開発の敷居が高くなってしまうということで close