Feat/ユーザー登録画面
saitamau-maximum/maxitter pull request #97
Opened 2023-11-21 13:06 UTC by nakamuraitsuki

ReactRouterが欲しかったのでdevelopmentをマージしました。そのため、マイグレーション.goとモデル.goが無くなりました。

2023-11-21 14:14 UTC, sor4chi commented
まずい。node_modulesがコミットされてしまっている

2023-11-22 01:59 UTC, nakamuraitsuki commented
React Router導入の際に新しいnode_modulesができてしまったようです。修正します

2023-11-22 02:14 UTC, sor4chi commented
消せてなさそう

2023-11-22 02:19 UTC, sor4chi commented
Gitの「削除」には2パターンあって、「消したっていうコミットをする」っていうのと「そもそも追加したコミットを改変して無かったことにする」っていうのがあります。

node_modulesをtracking(Git管理下)から外して欲しいのには2つ理由があって

- 更新頻度が多いため、毎回コミットでnode_modulesが更新されコンフリクト祭りになる
- そもそも容量がクソでかいので毎回pushやpullで大量の通信が発生し、CI/ビルド時間等が長くなる

という感じです。

最初にあげた「追加した後に消した」っていうコミットをして消す方法でも一応消えはするんですが、コミットには全ての変更履歴が含まれクソでかnode_modulesの更新履歴を毎回ダウンロードすることになるため、rebase/force-pushを用いた歴史改変の削除をすることをお勧めします。

2023-11-22 14:09 UTC, a01sa01to commented
`node_modules` はおっけー！
ただ `/package.json`, `/package-lock.json` も必要ないので消しておいていただけると！
(`/frontend/package.json` ではないので注意)

2023-12-04 10:49 UTC, nakamuraitsuki commented
消せたと思います、確認よろしくお願いします。

2023-12-04 11:10 UTC, sor4chi commented
よさげ

2023-12-08 15:24 UTC, sor4chi requested changes
お願いします！
まだユーザー選んで投稿する機能はできてないっていう認識で合ってるかな？

2023-12-08 15:24 UTC, sor4chi commented on frontend/src/App.jsx
> +            <Route  path="/Registration" element={<Registration />}></Route>
パス名は小文字or数字orハイフンにしましょう！

2023-12-08 15:24 UTC, sor4chi commented on frontend/src/pages/Home.jsx
> +        <Link to={"/Registration"}>ユーザー登録</Link>
これも

2023-12-10 05:06 UTC, nakamuraitsuki commented
[https://github.com/saitamau-maximum/maxitter/pull/83](url)
これですでにユーザーを選択して投稿する機能ができていると思っています。

2023-12-10 05:32 UTC, sor4chi approved these changes
![LGTM](https://images.lgtmgen.org/2b47091b-9277-4d94-9056-a15fafa097fe)

2023-12-10 10:49 UTC, a01sa01to approved these changes
すみません見逃していました！たぶんよさそう

2023-12-10 10:49 UTC, merged